training_args:

  ### Training Config ###
  learning_rate: 0.000002                       # VAE Training Learning Rate
  lr_scheduler: constant_with_warmup            # LR Scheduler
  lr_warmup_steps: 25000                        # LR Warmup Steps
  total_training_iterations: 400000             # Total Training Iterations
  checkpoint_iterations: 5000                   # Checkpoint Iteration Frequency
  per_gpu_batch_size: 16                        # Batch per GPU (multipled by n_gpus in accelerate)
  gradient_accumulations_steps: 1               # Split per GPU batch into accumulation steps
  max_grad_norm: 1.0                            # Max Grad Norm for Clipping
  num_val_random_samples: 8                     # How many random samples do you want to plot reconstructions for? (max of the set batch per gpu)
  val_img_folder_path: null                     # Folder of images you want to plot during training, if you dont want to random sample
  val_generation_freq: 1000                     # How often do you want to test generations?
  pixelwise_average: True                       # Do you want to average all the pixels (True) or sum pixels and average the batch (False)
  optimizer_beta1: 0.9                          # VAdamW Optimizer Beta1
  optimizer_beta2: 0.999                        # AdamW Optimizer Beta2
  optimizer_weight_decay: 0.005                 # AdamW Optimizer Weight Decay

  ### Diffusion Config ###
  loss_fn: mse                                  # What loss function do you want to use?
  num_diffusion_timesteps: 1000                 # How many steps of noising/denoising do you want?
  beta_start: 0.0001                            # Beta scheduler start
  beta_end: 0.02                                # Beta scheduler end
  cfg_dropout_prob: 0.1                         # Classifier free guidance context dropout

  ### Dataset Config ###
  pin_memory: True                              # Do you want to pin_memory on Dataloader?
  num_workers: 32                               # Number of CPU workers for DataLoading
  random_resize: False                          # Do you want to random resize in image transforms. If false, defauls to resize
  interpolation: bilinear                       # What interpolation mode do you want to use? ("nearest", "bilinear", "bicubic")
  random_flip_p: 0.0                            # Random Horizontal Flip Probability
  pre_encoded_text: True                        # Is you text pre-encoded or will we encode them as they come?
